"""Person 2 VAE experiment: scoring comparison + beta ablation.

This script trains the VAE for several beta values and evaluates each trained
model with two anomaly scores:
  1. mse: deterministic reconstruction error baseline.
  2. reconstruction_probability: Monte-Carlo negative log reconstruction probability.

Example:
    python scripts/run_vae_ablation.py --epochs 20 --betas 0.5 1.0 2.0 --seeds 0 1 2
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import statistics
import sys
from collections import defaultdict

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.data import get_fashion_mnist_oneclass  # noqa: E402
from src.evaluation import evaluate  # noqa: E402
from src.models.vae import VAEAD  # noqa: E402
from src.utils import get_device, set_seed  # noqa: E402


def _safe_beta(beta: float) -> str:
    return str(beta).replace(".", "p")


def _mean_std(values: list[float]) -> tuple[float, float]:
    if len(values) == 1:
        return values[0], 0.0
    return statistics.mean(values), statistics.stdev(values)


def _write_csv(path: str, rows: list[dict], fields: list[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _write_markdown(path: str, summary_rows: list[dict]) -> None:
    lines = [
        "# Person 2 — VAE beta ablation\n",
        "| beta | score_method | AUROC mean ± std | PR-AUC mean ± std | best-F1 mean ± std |",
        "|---:|---|---:|---:|---:|",
    ]
    for r in summary_rows:
        lines.append(
            f"| {r['beta']} | {r['score_method']} | "
            f"{r['auroc_mean']:.4f} ± {r['auroc_std']:.4f} | "
            f"{r['pr_auc_mean']:.4f} ± {r['pr_auc_std']:.4f} | "
            f"{r['best_f1_mean']:.4f} ± {r['best_f1_std']:.4f} |"
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _write_latex_snippet(path: str, summary_rows: list[dict]) -> None:
    rows = [
        "% Auto-generated by scripts/run_vae_ablation.py",
        "\\begin{table}[h]",
        "\\centering",
        "\\caption{Person 2 VAE beta ablation on the Fashion-MNIST one-class setting.}",
        "\\label{tab:vae-beta-ablation}",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "$\\beta$ & Score & AUROC & PR-AUC & Best-F1 \\\\ ",
        "\\midrule",
    ]
    for r in summary_rows:
        score = "MSE" if r["score_method"] == "mse" else "Recon. probability"
        rows.append(
            f"{r['beta']} & {score} & "
            f"{r['auroc_mean']:.4f} $\\pm$ {r['auroc_std']:.4f} & "
            f"{r['pr_auc_mean']:.4f} $\\pm$ {r['pr_auc_std']:.4f} & "
            f"{r['best_f1_mean']:.4f} $\\pm$ {r['best_f1_std']:.4f} \\\\"
        )
    rows.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(rows))


def _plot_beta(summary_rows: list[dict], results_dir: str, metric: str) -> None:
    plt.figure(figsize=(5, 3.5))
    for method in sorted({r["score_method"] for r in summary_rows}):
        sub = sorted([r for r in summary_rows if r["score_method"] == method], key=lambda x: x["beta"])
        xs = [float(r["beta"]) for r in sub]
        ys = [float(r[f"{metric}_mean"]) for r in sub]
        yerr = [float(r[f"{metric}_std"]) for r in sub]
        plt.errorbar(xs, ys, yerr=yerr, marker="o", capsize=3, label=method)
    plt.xlabel("beta")
    plt.ylabel(metric.upper().replace("_", "-"))
    plt.title(f"VAE beta ablation — {metric.upper().replace('_', '-')}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(results_dir, f"vae_beta_{metric}.png"), dpi=130)
    plt.close()


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--betas", type=float, nargs="+", default=[0.5, 1.0, 2.0])
    p.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--normal-class", type=int, default=0)
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--anomaly-per-class", type=int, default=200)
    p.add_argument("--latent-dim", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--mc-samples", type=int, default=10)
    p.add_argument("--results-dir", default="results/vae_ablation")
    p.add_argument("--report-dir", default="report")
    args = p.parse_args()

    os.makedirs(args.results_dir, exist_ok=True)
    device = get_device()
    print(f"device={device} normal_class={args.normal_class}")

    run_rows: list[dict] = []
    score_methods = ["mse", "reconstruction_probability"]

    for seed in args.seeds:
        set_seed(seed)
        train_loader, test_loader = get_fashion_mnist_oneclass(
            normal_class=args.normal_class,
            batch_size=args.batch_size,
            anomaly_test_per_class=args.anomaly_per_class,
            seed=seed,
        )

        for beta in args.betas:
            print(f"\n=== VAE beta={beta:g} seed={seed} ===")
            model = VAEAD(
                latent_dim=args.latent_dim,
                lr=args.lr,
                beta=beta,
                score_method="reconstruction_probability",
                mc_samples=args.mc_samples,
                device=device,
            )
            history = model.fit(train_loader, epochs=args.epochs)

            for method in score_methods:
                model.score_method = method
                tag = f"vae_beta{_safe_beta(beta)}_seed{seed}_{method}"
                metrics = evaluate(model, test_loader, results_dir=args.results_dir, tag=tag, history=history)
                row = {
                    "beta": beta,
                    "seed": seed,
                    "score_method": method,
                    "auroc": metrics["auroc"],
                    "pr_auc": metrics["pr_auc"],
                    "best_f1": metrics["best_f1"],
                    "best_threshold": metrics["best_threshold"],
                    "n_normal": metrics["n_normal"],
                    "n_anomaly": metrics["n_anomaly"],
                }
                run_rows.append(row)
                print(
                    f"beta={beta:g} seed={seed} method={method}: "
                    f"AUROC={row['auroc']:.4f} PR-AUC={row['pr_auc']:.4f} best-F1={row['best_f1']:.4f}"
                )

    run_fields = [
        "beta", "seed", "score_method", "auroc", "pr_auc", "best_f1",
        "best_threshold", "n_normal", "n_anomaly",
    ]
    _write_csv(os.path.join(args.results_dir, "vae_ablation_runs.csv"), run_rows, run_fields)

    grouped = defaultdict(list)
    for r in run_rows:
        grouped[(float(r["beta"]), r["score_method"])].append(r)

    summary_rows = []
    for (beta, method), rows in sorted(grouped.items()):
        auroc_mean, auroc_std = _mean_std([float(r["auroc"]) for r in rows])
        pr_auc_mean, pr_auc_std = _mean_std([float(r["pr_auc"]) for r in rows])
        best_f1_mean, best_f1_std = _mean_std([float(r["best_f1"]) for r in rows])
        summary_rows.append({
            "beta": beta,
            "score_method": method,
            "auroc_mean": auroc_mean,
            "auroc_std": auroc_std,
            "pr_auc_mean": pr_auc_mean,
            "pr_auc_std": pr_auc_std,
            "best_f1_mean": best_f1_mean,
            "best_f1_std": best_f1_std,
            "n_runs": len(rows),
        })

    summary_fields = [
        "beta", "score_method", "auroc_mean", "auroc_std", "pr_auc_mean",
        "pr_auc_std", "best_f1_mean", "best_f1_std", "n_runs",
    ]
    _write_csv(os.path.join(args.results_dir, "vae_ablation_summary.csv"), summary_rows, summary_fields)
    _write_markdown(os.path.join(args.results_dir, "vae_ablation_summary.md"), summary_rows)
    with open(os.path.join(args.results_dir, "vae_ablation_results.json"), "w", encoding="utf-8") as f:
        json.dump({"runs": run_rows, "summary": summary_rows, "args": vars(args)}, f, indent=2)

    _plot_beta(summary_rows, args.results_dir, "auroc")
    _plot_beta(summary_rows, args.results_dir, "pr_auc")

    _write_latex_snippet(
        os.path.join(args.report_dir, "vae_results_snippet.tex"),
        summary_rows,
    )

    print("\nWrote:")
    print(f"  {args.results_dir}/vae_ablation_runs.csv")
    print(f"  {args.results_dir}/vae_ablation_summary.csv")
    print(f"  {args.results_dir}/vae_ablation_summary.md")
    print(f"  {args.results_dir}/vae_ablation_results.json")
    print(f"  {args.report_dir}/vae_results_snippet.tex")


if __name__ == "__main__":
    main()
